# :A: tldr GitHub Action for automated releases with changesets
# :A: ctx This workflow runs after CI passes and code is merged to main
# :A: ctx The CI workflow validates all PRs before they can be merged
name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Check for changes between main and changeset-release/main
        id: check_changes
        run: |
          # :A: ctx Check if changeset-release/main branch exists and has differences
          # Fetch the changeset-release/main branch if it exists
          git fetch origin changeset-release/main:refs/remotes/origin/changeset-release/main || echo "changeset-release/main doesn't exist yet"
          # Check if there are any differences
          if git rev-parse --verify origin/changeset-release/main >/dev/null 2>&1; then
            # Branch exists, check for differences
            if git diff --quiet HEAD origin/changeset-release/main; then
              echo "has_changes=false" >> $GITHUB_OUTPUT
              echo "No changes detected between main and changeset-release/main"
            else
              echo "has_changes=true" >> $GITHUB_OUTPUT
              echo "Changes detected between main and changeset-release/main"
            fi
          else
            # If changeset-release/main doesn't exist, we have changes
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "changeset-release/main branch doesn't exist, proceeding with release"
          fi

      - name: Create Release Pull Request or Publish
        if: steps.check_changes.outputs.has_changes == 'true'
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          version: pnpm version
          commit: "chore: version packages"
          title: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}